{
 "title": "MedVisit",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency (0.5) - Booking Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(booking_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95) - BookingService",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(booking_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99) - Booking Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(booking_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (max) - Booking Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max(sum(rate(booking_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество запросов на бронирование",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(booking_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число неуспешных бронирований",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(failed_bookings_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate Booking Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(failed_bookings_total[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Booking Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum by (method) (rate(booking_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.5) - Nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95) - Nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99) - Nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(Max) - Nginx ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "max(rate(nginx_ingress_controller_response_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS - Nginx ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate - Nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}