apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "payment-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "payment-service.labels" . | nindent 8 }}
    spec:
      containers:
        - name: payment-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}   
          env:
            - name: Endpoints__AuthService
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Endpoints__AuthService   
            - name: JwtSettings__Key
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JwtSettings__Key
            - name: PostgresConnection__Host
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PostgresConnection__Host
            - name: PostgresConnection__Port
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PostgresConnection__Port
            - name: PostgresConnection__Database
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PostgresConnection__Database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
