apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: notification-service
type: Opaque
data:
  DB_USERNAME: bm90aWZpY2F0aW9u 
  DB_PASSWORD: bm90aWZpY2F0aW9u
  RABBIT_USER: cmFiYml0bXE= 
  RABBIT_PASSWORD: cmFiYml0bXE=

