apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: booking-service
data:
  PostgresConnection__Host: {{ .Values.postgresql.postgresqlHost }}
  PostgresConnection__Port: "5432"
  PostgresConnection__Database: {{ .Values.postgresql.postgresqlDatabase }}
  Endpoints__PaymentService: {{ .Values.endpoints.paymentService}}
  Endpoints__AuthService: {{ .Values.endpoints.authService}}
  Endpoints__ScheduleService: {{ .Values.endpoints.scheduleService}}
  RabbitMq__Host: {{ .Values.rabbitmq.host }}
  Redis__Host: {{ .Values.redis.host }}