apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: booking-service
type: Opaque
data:
  DB_USERNAME: Ym9va2luZw== 
  DB_PASSWORD: Ym9va2luZw==
  RABBIT_USER: cmFiYml0bXE= 
  RABBIT_PASSWORD: cmFiYml0bXE=

