apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accessmanagement-ingress
  namespace: accessmanagement-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx 
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: accessmanagement-service
                port:
                  number: 8080
          - path: /account
            pathType: Prefix
            backend:
              service:
                name: accessmanagement-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  namespace: auth-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx 
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: auth-service-medvisit-authserver
                port:
                  number: 8080

          - path: /register
            pathType: Prefix
            backend:
              service:
                name: auth-service-medvisit-authserver
                port:
                  number: 8080
                  
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service-medvisit-authserver
                port:
                  number: 8080                 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-service
  namespace: payment-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-service
  namespace: booking-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /booking
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-service
  namespace: notification-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080

         
         