{
 "title": "AuthManager Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency (0.5) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(user_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(user_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(user_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Max) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max(sum(rate(user_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(user_requests_total[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (500 responses) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(user_errors_total[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS - Nginx Ingress ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (500 responces) - Nginx Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_requests{status=\"500\"}[1m]))) / sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.5) - Nginx Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95) - Nginx Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99) - Nginx Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(Max) - Nginx Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "max(rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    { "expr": "pg_stat_database_xact_commit", "legendFormat": "__auto" }
   ]
  }
 ]
}