auth:
  enabled: false

architecture: standalone  


master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 6379

livenessProbe:
  enabled: true
readinessProbe:
  enabled: true
