apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  PostgresConnection__Host: {{ .Values.postgresql.postgresqlHost }}
  PostgresConnection__Port: "5432"
  PostgresConnection__Database: {{ .Values.postgresql.postgresqlDatabase }}
  JwtSettings__Key: {{ .Values.jwtSettings.key }}
  Endpoints__PaymentService: {{ .Values.endpoints.paymentService}}