apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "medvisit-authserver.fullname" . }}
  labels:
    {{- include "medvisit-authserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "medvisit-authserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "medvisit-authserver.labels" . | nindent 8 }}
    spec:
      containers:
        - name: medvisit-authserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: JwtSettings__Key
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: JwtSettings__Key
            - name: Endpoints__PaymentService
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: Endpoints__PaymentService
            - name: PostgresConnection__Host
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: PostgresConnection__Host
            - name: PostgresConnection__Port
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: PostgresConnection__Port
            - name: PostgresConnection__Database
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: PostgresConnection__Database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_PASSWORD
